POST http://localhost:3333/sign-up
Content-Type: application/json

{
  "name": "joao",
  "email": "joaov@mail.com",
  "password": "123456"
}

###

POST http://localhost:3333/sign-in
Content-Type: application/json

{
  "email": "joaov@gmail.com",
  "password": "joaovl"
}

###

POST http://localhost:3333/clients
Content-Type: application/json
Authorization: Bearer token

{
  "name": "André Vinnicius",
  "role": "PEOPLE",
  "address": {
    "city": "Brasília",
    "street": "Rua Dom Alfredo Cavalcante",
    "number": 201
  }
}

###

GET http://localhost:3333/clients
Authorization: Bearer token

###

GET http://localhost:3333/clients/clqfb2h8t00022tou77tagvx0
Authorization: Bearer token

###

DELETE http://localhost:3333/clients/clqfb2h8t00022tou77tagvx0
Authorization: Bearer token

###

GET http://localhost:3333/u/clqb0kr9r0000ue1v6bjalpj4
Authorization: Bearer token
